Style/Documentation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Metrics/BlockLength:
  Enabled: false